### ISSUE TITLE
Update node-fetch dependency

### ISSUE THREAD

**Issue by wdhorton** [matthew-andrews/isomorphic-fetch#103]
node-fetch is on release `1.6.0`, and this library is still depending on `^1.0.1`. Updating the dependency would give access to newer features added to `node-fetch`, like response.buffer.

**Comment by caoyangs** [comment]
Doesn't `^1.0.1` pick up `1.6.0`?

**Comment by RusAlex** [comment]
@caoyangs 

Regarding https://github.com/npm/node-semver

> Caret ranges are ideal when an author may make breaking changes between 0.2.4 and 0.3.0 releases, which is a common practice. However, it presumes that there will not be breaking changes between 0.2.4 and 0.2.5. It allows for changes that are presumed to be additive (but non-breaking), according to commonly observed practices.
^1.2.3 := >=1.2.3 <2.0.0
^0.2.3 := >=0.2.3 <0.3.0
^0.0.3 := >=0.0.3 <0.0.4

^1.0.1 it's fixed to version 1.0.1 and 1.0.2  won't be picked up.

**Comment by shri3k** [comment]
> ^1.0.1 it's fixed to version 1.0.1 and 1.0.2 won't be picked up.

Not true. That's only applicable if it's a fixed version number w/o `^`. 
`^` usually allows changes for `minor` and `patch` versions except for left-most zero based versions which are considered breaking changes.
So, `^0.1.0` ranges to `>=0.1.0 < 0.2.0` and `^0.0.1` ranges only to `=>0.0.1 < 0.0.2` however, `^1.0.0` will allow ranges to `>=1.0.0 < 2.0.0`.

From that same link:-
>Allows changes that do not modify the left-most non-zero digit in the [major, minor, patch] tuple. In other words, this allows patch and minor updates for versions 1.0.0 and above, patch updates for versions 0.X >=0.1.0, and no updates for versions 0.0.X.

**Comment by dandv** [comment]
:+1: Wondering if @matthew-andrews still has time to maintain this package.

**Comment by dandv** [comment]
@shri3k is right. I've just tested:

```
% cat package.json
{
  "name": "if",
  "version": "1.0.0",
  "description": "Test isomorphic-fetch semver",
  "main": "index.js",
  "dependencies": {
    "node-fetch": "^1.0.1"
  }
}
% npm install     
if@1.0.0 /home/dandv/if
└─┬ node-fetch@1.6.1 
  ├─┬ encoding@0.1.12 
  │ └── iconv-lite@0.4.13 
  └── is-stream@1.1.0 
```

**Comment by matthew-andrews** [comment]
i believe this isn't necessary and can be closed
