### ISSUE TITLE
How to close fetch output?

### ISSUE THREAD

**Issue by qiaolb** [matthew-andrews/isomorphic-fetch#108]
How to close the console output? 
For example:
Fetch complete: GET "http://....."

**Comment by aliankarali** [comment]
It falls under the debug sections of console logs. surely there must be a way to disable them?

**Comment by aliankarali** [comment]
I realized that the console outputs are generated as long as the console is open though. So it is fine.

**Comment by qiaolb** [comment]
I found Not all Chrome are like this. Maybe, it is other reason.

**Comment by aliankarali** [comment]
If you disable Log XMLHttpRequests option in console settings it doesn't.
