### ISSUE TITLE
Cookies are not being received when a `set-cookie` header is present in response

### ISSUE THREAD

**Issue by rohannair** [matthew-andrews/isomorphic-fetch#110]
From my understanding of [receiving cookies](https://github.com/github/fetch#receiving-cookies), a `set-cookie` header containing a cookie with same location as the client should set the cookie. 

In my network request, I see that header being sent:
<img width="644" alt="screenshot 2016-10-19 14 44 29" src="https://cloud.githubusercontent.com/assets/3764902/19532630/929f5b44-960a-11e6-8c79-1dca1612930e.png">
<img width="1130" alt="screenshot 2016-10-19 14 44 18" src="https://cloud.githubusercontent.com/assets/3764902/19532633/9541efc4-960a-11e6-83ea-a27c88f9c759.png">

But it does not actually set the cookie...
<img width="963" alt="screenshot 2016-10-19 14 01 00" src="https://cloud.githubusercontent.com/assets/3764902/19532616/788032ce-960a-11e6-8c6a-0add3fb942a2.png">

**Comment by Blackening999** [comment]
@rohannair have you solved it?
