### ISSUE TITLE
es6-promise is not a safe polyfill to recommend in your readme

### ISSUE THREAD

**Issue by nilliams** [matthew-andrews/isomorphic-fetch#111]
es6-promise's strict spec handling of uncaught exceptions (by not doing so at all) is a footgun. I don't feel like it should be the default recommendation of polyfill, and personally is the reason I've kept my team away from `fetch()` for months. Here are examples why:
- http://requirebin.com/?gist=8f13d5147c1c252ab1691115bfa8b7c5
- http://requirebin.com/?gist=06e8c85fcaca56c9651c6aabd0d91476

Bluebird, however does the right thing:
- http://requirebin.com/?gist=43a3858fa57d9b94c00b2b454722c15d

I'm not saying Bluebird should be what you suggest instead, as I haven't dug into relative sizes/support/practicalities of that. I just feel that recommending people use es6-promise is going to cause a lot of people pain.

**Comment by ysmood** [comment]
Maybe you could give [yaku](https://github.com/ysmood/yaku) a try.

# Features

- The minified file is only 4.1KB (1.8KB gzipped)
- Supports "uncaught rejection" and "long stack trace", [Comparison][docs/debugHelperComparison.md]
- Designed to work on IE5+ and other major browsers
- 100% statement and branch test coverage
- Much better performance than the native Promise
- Well commented source code with every Promises/A+ spec

**Comment by nilliams** [comment]
Yaku looks excellent, and ticks all my personal boxes, thank you!

I've been trying to pin this down even more, because when I actually hit it I felt it was way worse than I've actually demonstrated. And I remembered that even when you .catch() and re-raise, es6-promise does NOT surface the error/exception.

To me this is the most concrete example that the developer is absolutely doing all the right things, and the error is STILL swallowed:

http://requirebin.com/?gist=9c59be0170fa7691a534705daf6b765d

And (now using Yaku as alternative), here's how you do it right:

http://requirebin.com/?gist=8e1d11f8754e58afd271a994760bb0c4

**Comment by ysmood** [comment]
If you have any problem with Yaku, please feel free to issue me. The project is quite active to user feedbacks now.

**Comment by nilliams** [comment]
To make matters even worse the author has now closed that issue thread, so it's not even visible to people now that it's an issue: https://github.com/stefanpenner/es6-promise/issues/70

**Comment by ysmood** [comment]
Sad story.

**Comment by developit** [comment]
I would recommend looking at promise-polyfill. I tested a bunch of polyfills and it's the smallest and I don't think it has that footgun.

**Comment by matthew-andrews** [comment]
This repo no longer recommends any polyfill.
