### ISSUE TITLE
Internally, switch to the server-side implementation of window.fetch

### ISSUE THREAD

**Issue by bitinn** [matthew-andrews/isomorphic-fetch#12]
https://github.com/bitinn/node-fetch

To me the idea of running browser polyfill on node seems weird, so I decide to make a server-side only version, I would be glad if it turns out to be useful at all.

**Comment by matthew-andrews** [comment]
Nice!

**Comment by matthew-andrews** [comment]
I'll switch to it asap.  I still think there's value in the isomorphic-ness of this library but it would so good to drop the XMLHttpRequest polyfill—we've found loads of issues with it and it doesn't seem actively maintained anymore :disappointed:.

**Comment by bitinn** [comment]
Yeah, I was thinking along the same line: not even browser vendors managed to have a consistent `XMLHttpRequest` implementation across the board, let's not tackle that burning mountain.

**Comment by matthew-andrews** [comment]
released in `v2.0.0`
