### ISSUE TITLE
Cannot set header in SPA?

### ISSUE THREAD

**Issue by tronghiep92** [matthew-andrews/isomorphic-fetch#122]
Hi all,
I have a code example:
```
fetch(URL, {
    'GET',
    body: JSON.stringify(data),
    headers: {
      'Content-Type': 'application/json',
      'Foobaz': 1234567
    },
  })
```

With app SPA, I cannot get my header.

Please help, thanks!!!!!

![error](https://cloud.githubusercontent.com/assets/4768095/22882436/9d48c2dc-f21d-11e6-83a6-a1e0c0f7e95c.png)

**Comment by lmj0011** [comment]
maybe try making the `Foobaz` value a string

also change your method to `POST` if you're sending a body
GET passes data in the form of a query string (eg. `foo=2&bar=2`)

```js
fetch(URL, {
    'GET',
    body: JSON.stringify(data),  // <---  GET doesn't have a body, has to be a query string
    headers: {
      'Content-Type': 'application/json',
      'Foobaz': '1234567'  // <---  1234567 to '1234567'
    },
  })
```

**Comment by olieidel** [comment]
Have you set `mode` to `no-cors` (for development) by any chance? In that case, it's not possible to set the `Content-Type` header, as seen [here](https://github.com/github/fetch/issues/318#issuecomment-249573195).

Just tripped over this myself and lost 2 hours, hope it helps.

**Comment by itsazzad** [comment]
@tronghiep92 How did you solve that?

**Comment by tronghiep92** [comment]
@itsazzad I've switched to [axios](https://github.com/axios/axios) 😄
