### ISSUE TITLE
easier way to send body for GET request?

### ISSUE THREAD

**Issue by littlehome-eugene** [matthew-andrews/isomorphic-fetch#126]
For post request, we could use javascript object as a data.  

For get request, we need to transform the data into url params and append to the url.  

Is there a easier (hopefully unified) way of sending POST/GET data to server when using isomorphic-fetch?

**Comment by matthew-andrews** [comment]
I think this is a fundamental question about the way HTTP itself is designed.  I don't think I'm really qualified to answer it.

I found this thread on StackOverflow which seemed relevant and interesting:-
http://stackoverflow.com/questions/978061/http-get-with-request-body
