### ISSUE TITLE
Make it *not* use window.fetch if it is available

### ISSUE THREAD

**Issue by Noitidart** [matthew-andrews/isomorphic-fetch#131]
Is there a way to force isomorphic-fetch to force use polyfill? Even if window.fetch exists? Because in Microsoft Edge all `fetch` requests are failing - http://stackoverflow.com/a/43580982/1828637

**Comment by paulmelnikow** [comment]
If you don't find a way to do this with isomorphic-fetch, you can do it with [fetch-ponyfill](https://github.com/qubyte/fetch-ponyfill), which will always give you the whatwg implementation.

**Comment by Noitidart** [comment]
Very cool thank you @paulmelnikow !

**Comment by matthew-andrews** [comment]
I think @paulmelnikow suggestion is the best way to achieve what you're after.  isomorphic-fetch simply passes all `fetch` logic to [`whatwg-fetch`](https://github.com/github/fetch) — so not really an easy way I can think of to force using the polyfill.
