### ISSUE TITLE
Which files need to be hosted on cdnjs?

### ISSUE THREAD

**Issue by dakshshah96** [matthew-andrews/isomorphic-fetch#132]
Hi, I'd like to host your library, isomorphic-fetch on [cdnjs](https://github.com/cdnjs/cdnjs) — It is one of the most famous free and public web front-end CDN services which is used by [~1,143,000 websites](https://trends.builtwith.com/cdn/CDN-JS) worldwide.

There are three files which seem relevant to me in your repository:
```
fetch-bower.js
fetch-npm-browserify.js
fetch-npm-node.js
```

Which files out of the ones listed above will work in a browser and let developers use your library directly? Also, please let me know if there are any other files that should be hosted.

**Comment by matthew-andrews** [comment]
I think none of them will work on their own in the browser…  It needs to be compiled via browserify / babel etc to work in the browser.

**Comment by matthew-andrews** [comment]
(Also thank you for your kind message and interest)

**Comment by dakshshah96** [comment]
@matthew-andrews Thanks for letting me know! 😄

**Comment by PeterDaveHello** [comment]
Hi @matthew-andrews, is it possible to provide it in the repository? Since one of your users is asking CDNJS to host it :)

**Comment by matthew-andrews** [comment]
I don't really like to commit built files into repositories…  Could you pull the file from a web service that `npm install`'s and webpack's the module instead?  e.g.
https://www.ft.com/__origami/service/build/v2/bundles/js?modules=isomorphic-fetch@^2.2.1

**Comment by matthew-andrews** [comment]
or this one:-
https://wzrd.in/bundle/isomorphic-fetch

**Comment by PeterDaveHello** [comment]
hmmmm ... we don't support that yet.
