### ISSUE TITLE
405: Method Not Allowed

### ISSUE THREAD

**Issue by charleylla** [matthew-andrews/isomorphic-fetch#134]
when I open a post request, it doesn't work well, what's wrong with my code?
p.s. get method works well.

```
try{
	const URL = config.LOGIN;
	const data = await fetch(URL,{
		method:"POST",
		headers:{
			"Accept": "application/json",
		    "Content-Type": "application/json"
		},
		body:JSON.stringify({
			"a":1,
			"b":2
		})
	}).then((response)=>{
		return response.json();
	});

	console.log(data)
}catch(e){
	alert(e)
}
```
and browser reports an error: **405: Method Not Allowed**

get request works fine
```
const data = await fetch(URL).then((res)=>{
    return res.json()
});
```

Thanks!

**Comment by jackfranklin** [comment]
@charleylla you're better off posting this to StackOverflow - this isn't a bug with this module but probably one with your API or your JS - and this probably isn't the best environment for help on things like that :)

**Comment by charleylla** [comment]
thanks
