### ISSUE TITLE
UTF8 in get request

### ISSUE THREAD

**Issue by mulikaminker** [matthew-andrews/isomorphic-fetch#146]
For some reason, When I transfer Hebrew characters in get request it came as non-utf8. For example: áÜçÝ.

I add to the header request the line 'content-type': 'application/json; charset=utf-8',
'Accept': 'application/json; charset=utf-8', but it's do nothing. 

In a direct get call (from the browser or from postman it's work normal.

**Comment by webdeb** [comment]
Also an issue for äöüß

**Comment by matthew-andrews** [comment]
I'm sorry I didn't reply to this … I really doubt this is a problem caused by this library … if someone can make a reduced test case showing otherwise I'll be happy to consider a fix, however.
