### ISSUE TITLE
delete request with credentials included does not include cookies.

### ISSUE THREAD

**Issue by tinder-qhan** [matthew-andrews/isomorphic-fetch#149]
I have found that:
`fetch(url, { method: 'DELETE', credentials: 'include'})` will not send cookies for cross domain requests.
`fetch(url, { method: 'POST', credentials: 'include' })` will send cookies correctly for cross domain requests.

**Comment by matthew-andrews** [comment]
Hmm, I'm guessing you are talking about client side requests, and this module simply proxies the github fetch polyfill in that case, and so if there's a bug in that behaviour it's probably in that library.
