### ISSUE TITLE
Suggest more clear file naming

### ISSUE THREAD

**Issue by tracker1** [matthew-andrews/isomorphic-fetch#15]
Minor suggestion for a couple of renames...

* `client.js` => `fetch-bower.js`
* `npm-client.js` => `fetch-npm-browserify.js`
* `server.js` => `fetch-npm-node.js`

With a comment on the top indicating that each one runs in a given environment.. that `bower.json` will use `fetch-bower.js`, browserify will use `fetch-npm-browserify.js` and that node will otherwise use `fetch-npm-node.js` ... It wasn't quite as obvious to me at first glance.

This way all of the implementations are together, and clearly labelled into their role.

Does the client fetch return the fetch method from the module?

**Comment by matthew-andrews** [comment]
:+1: to everything.

**Comment by matthew-andrews** [comment]
[and yes the client fetch returns the return method from the fetch module]

**Comment by ryancole** [comment]
How does browserify know to use the browserify file? I'm confused.

**Comment by tracker1** [comment]
@ryancole iirc it's defined in package.json which file to use for browserify...
