### ISSUE TITLE
.FetchStream and .CookieJar missing?

### ISSUE THREAD

**Issue by mk-pmb** [matthew-andrews/isomorphic-fetch#150]
Compared to the regular `fetch` module, this one lacks `.FetchStream` and `.CookieJar` in v2.2.1. Could you add support for them please?

**Comment by matthew-andrews** [comment]
I believe it is correct for this module to not have support for these features as discussed here:-
https://github.com/marionebl/omni-fetch/issues/4#issuecomment-335334089
