### ISSUE TITLE
Introduce beta dist-tag

### ISSUE THREAD

**Issue by sbekrin** [matthew-andrews/isomorphic-fetch#152]
Currently node-fetch has `next` distribution tag [with lots of improvements and new features](https://github.com/bitinn/node-fetch/releases/tag/v2.0.0-alpha.9) (e.g. `.arrayBuffer()` response method).

Is it possible to bump all dependency versions to latest beta and publish this module with `next` dist-tag, so by running `npm i isomorphic-fetch@next` we would have latest versions, which makes it easier to test and plan upgrades, as well to have features developers missing?

Thanks.

**Comment by matthew-andrews** [comment]
I think this is now redundant (sorry again as per all the other issues for my lethargic replies to issues and PRs raised here)
