### ISSUE TITLE
unable to verify the first certificate?

### ISSUE THREAD

**Issue by sandywk** [matthew-andrews/isomorphic-fetch#154]
next.js + isomorphic-fetch

error:
`request to https://...... failed, reason: unable to verify the first certificate`

What should I do?

**Comment by voor** [comment]
Are you using a self-signed SSL certificate?

**Comment by lawrezzz** [comment]
what should i do if i am using a self-signed SSL?
any override method?

**Comment by sdgandhi** [comment]
@lawrezzz 

```javascript
const https = require("https");

const options = {
  agent: new https.Agent({
    rejectUnauthorized: false
  })
};

fetch(url, options)
```

**Comment by taynguyen** [comment]
In dev or test environment we should set
```
process.env.NODE_TLS_REJECT_UNAUTHORIZED = '0';
```

That would solve at env scope.
