### ISSUE TITLE
exported fetch is useless on client side

### ISSUE THREAD

**Issue by dimsmol** [matthew-andrews/isomorphic-fetch#16]
```
var fetch = require('isomorphic-fetch')
```

doesn't work on client side, because whatwg-fetch module exports nothing.

To make it work `npm-client.js` must look like
```
require('whatwg-fetch');
module.exports = fetch;
```
(instead of `module.exports = require('whatwg-fetch');`)

`client.js` has the same issue, I guess.

**Comment by mattlenz** [comment]
+1

**Comment by cesarandreu** [comment]
+1

**Comment by robertknight** [comment]
The documentation and example does state that requiring isomorphic-fetch modifies the global object for consistency with the native API. However being able to require/import it via the usual means makes it more obvious when reading the code.

**Comment by cesarandreu** [comment]
Thank you :D.
