### ISSUE TITLE
If there are big numbers in response, how can we process them?

### ISSUE THREAD

**Issue by djheart0710** [matthew-andrews/isomorphic-fetch#168]
In my project, I use fetch to process request. The result contains big numbers, which exceed the max number in JS. After response.json() , I got the data, but the big number data has already became wrong. For example, I got 14355897211814021 in Postman, but in project, I got 14355897211814020. How can I process the response got by fetch? Thanks!

**Comment by mderijcke** [comment]
This is how V8's `JSON.parse` works. You can use [lossless-json](https://www.npmjs.com/package/lossless-json) for this though.

Use it like this:

```js
const LosslessJSON = require('lossless-json');

setImmediate(async () => {
    let response = await fetch(/* ... */);

    let json = LosslessJSON.parse(await response.text());

    console.log(json);
});
```

**Comment by jimmywarting** [comment]
or perhaps use [json-bigint](https://www.npmjs.com/package/json-bigint)?

**Comment by matthew-andrews** [comment]
Interesting problem ! Believe your question has been answered … …
