### ISSUE TITLE
Allow to ignore SSL cert errors

### ISSUE THREAD

**Issue by tirthaguha** [matthew-andrews/isomorphic-fetch#172]
```
name: 'FetchError',
  message: 'request to https://localhost/xxx/xxx/xx failed, reason: self signed certificate',
  type: 'system',
  errno: 'DEPTH_ZERO_SELF_SIGNED_CERT',
  code: 'DEPTH_ZERO_SELF_SIGNED_CERT' }
```
there should be flags through which we can ignore SSL errors fro development.

**Comment by mdogadailo** [comment]
```javascript
const https = require("https");

const options = {
  agent: new https.Agent({
    rejectUnauthorized: false
  })
};

fetch(url, options)
```

**Comment by tirthaguha** [comment]
Nice workaround. Closing this one.

**Comment by GALLLASMILAN** [comment]
> ```js
> const https = require("https");
> 
> const options = {
>   agent: new https.Agent({
>     rejectUnauthorized: false
>   })
> };
> 
> fetch(url, options)
> ```

Hello, Your solution does not run for me in react (create-react-app) application. Is it an alternative for frontend developers?

**Comment by mdogadailo** [comment]
@GALLLASMILAN you can add exception to your browser. Open domain which has wrong certificate and confirm that you want to proceed.

**Comment by liudonghua123** [comment]
Seems like `unsafely-treat-insecure-origin-as-secure` in `chrome://flags/`.

see also https://w3c.github.io/webappsec-secure-contexts/.
