### ISSUE TITLE
Question fine tuning latency TLS Cipher Suites

### ISSUE THREAD

**Issue by pabx06** [matthew-andrews/isomorphic-fetch#173]
hello.
not sure if this related to to isomorphic-fetch or nodeJS.
i was wondering how can i fine tune cipher suites used for SSL/TLS communication with https server
i would like to improve perf and save CPU cycles by using fast cyphers with smallest possible key size. 
Thanks.

**Comment by matthew-andrews** [comment]
I'm sorry … I can't see how this would be related to isomorphic-fetch.
