### ISSUE TITLE
Concerns of usage of >= for whatwg-fetch version in package.json?

### ISSUE THREAD

**Issue by msafari** [matthew-andrews/isomorphic-fetch#174]
I just noticed in our dependency tree that `isomorphic-fetch` started pulling v3.0.0 of whatwg-fetch. 
I believe it's because this repo is using `>= 0.10.0` in package.json.
Is there a reason you're not using just a caret to be safe and stay in the closest major version? 
`>=` will pull in latest major version. 
What if it's a breaking version that's being pulled in?

**Comment by rafaellyra** [comment]
It is in fact a problem right now since [v3.0.0 is not working with webpack](https://github.com/github/fetch/issues/659)

**Comment by gfx** [comment]
+1

ping @matthew-andrews

**Comment by mbifulco** [comment]
@matthew-andrews we would love some insight/help with this - it's been blocking some important updates for my team.  Can you take a look at #177?

**Comment by matthew-andrews** [comment]
Hi sorry for the immense delay, I have updated to the latest versions of node-fetch and whatwg-fetch in master … and as part of that changed to `^` semver … …  planning to release as a major version once I'm happy this hasn't broken anything … … …
