### ISSUE TITLE
Upgrade node-fetch to >= 2.3.0 to fix semantic-release users that use styled-components

### ISSUE THREAD

**Issue by kopax** [matthew-andrews/isomorphic-fetch#179]
## Environment

We are experiencing issue on travis while using semantic-release.

This happen because of a package having being fixed `node-fetch@2.3.0` for semantic-release to work and styled-components having an outdated node-fetch through [isomorphic-fetch](https://github.com/matthew-andrews/isomorphic-fetch/issues/new).

Users that use both semantic-release and styled-components will have issues. 

- https://github.com/semantic-release/github/issues/129
- https://github.com/semantic-release/semantic-release/issues/995

## Related issues:

- https://github.com/styled-components/styled-components/issues/2247#issuecomment-442114941
- https://github.com/styled-components/css-to-react-native/issues/98
- https://github.com/facebook/fbjs/issues/325
- https://github.com/matthew-andrews/isomorphic-fetch/issues/179

## Reproduction

https://travis-ci.org/yeutech-lab/rollup-umd-documentation/jobs/459847412

```bash
$ npm ls node-fetch
@yeutech-lab/rollup-umd-documentation@2.4.2 /home/dka/workspace/github.com/yeutech-lab/rollup-umd-documentation
├─┬ @semantic-release/github@5.2.5
│ └─┬ @octokit/rest@16.0.1
│   └── node-fetch@2.3.0 
└─┬ styled-components@4.1.1
  └─┬ css-to-react-native@2.2.2
    └─┬ fbjs@0.8.17
      └─┬ isomorphic-fetch@2.2.1
        └── node-fetch@1.7.3 
```

## Steps to reproduce

- semantic-release: v15.12.1
- styled-components: v4.1.1

## Expected Behavior

To have `node-fetch@2.3.0`

## Actual Behavior

Styled-components bring `node-fetch@1.7.3` and breaks semantic-release.

## Solution

- **short term**: `npm install node-fetch@2.3.0 --save-dev`
- **long term**: Upgrade chain of dependencies, require help of https://github.com/matthew-andrews/isomorphic-fetch/, https://github.com/facebook/fbjs, https://github.com/styled-components/css-to-react-native/ and https://github.com/styled-components/styled-components

**Comment by Otto-AA** [comment]
The last commit on isomorphic-fetch was more than three years ago, I fear that this won't be fixed anytime soon...

If you can switch the libraries used, I would recommend to use [cross-fetch](https://github.com/lquixada/cross-fetch) instead. It is basically the same as isomorphic-fetch, but with updated dependencies.

**Comment by matthew-andrews** [comment]
Hi sorry for the immense delay, I have updated to the latest versions of node-fetch and whatwg-fetch in master … planning to release as a major version once I'm happy this hasn't broken anything … … …
