### ISSUE TITLE
Fix version of whatwg-fetch

### ISSUE THREAD

**Issue by kopax** [matthew-andrews/isomorphic-fetch#181]
Version 3.0.0 is causing issue.

```
└─┬ @yeutech-lab/test-polyfill@1.1.3
  ├─┬ isomorphic-fetch@2.2.1
  │ └── whatwg-fetch@3.0.0 
```

For some reason, the way it is set in package.json install the 3.0, 

This ticket is for settings whatwg-fetch in the package.json

**Comment by matthew-andrews** [comment]
Hi sorry for the immense delay, I have updated to the latest versions of node-fetch and whatwg-fetch in master … planning to release as a major version once I'm happy this hasn't broken anything … … …
