### ISSUE TITLE
AbortController not working with this library

### ISSUE THREAD

**Issue by quorth0n** [matthew-andrews/isomorphic-fetch#185]
The following code results in the fetch executing as normal with no termination.
```js
  require('isomorphic-fetch');

  const controller = new AbortController();

  setTimeout(() => {
    controller.abort();
  }, 2000);

  return fetch(url, { signal: controller.signal })
    .then(response => {
      return response;
    })
    .catch(error => {
      throw new Error(error.message);
    });
```
Using node-fetch instead of this library allowed me to fix this issue with no other implementation changes.

**Comment by eeeman1** [comment]
what solutions were found?

**Comment by whirish** [comment]
@eeeman1 using node-fetch :)

**Comment by atuttle** [comment]
I created [@atuttle/smart-fetch](https://github.com/AlumnIQ/AlumnIQ/pull/13221) which adds AbortController into the mix, among other things.

**Comment by matthew-andrews** [comment]
I believe this will be coming in the next version of this package.
