### ISSUE TITLE
Is this library still been maintained?

### ISSUE THREAD

**Issue by jasonyin** [matthew-andrews/isomorphic-fetch#187]
Last release was in 2015, is it still been maintained?

**Comment by BenZed** [comment]
What maintenance does it need?

**Comment by dandv** [comment]
No. See [cross-fetch](https://github.com/lquixada/cross-fetch#why-not-isomorphic-fetch).

**Comment by matthew-andrews** [comment]
Sorry for the huge delay. I will release a major version soon, please test it against your applications.

**Comment by dandv** [comment]
Thanks @matthew-andrews. Since a lot of folks have switched to cross-fetch, would it be worth adding a section in the README comparing the two? Similar to the [`got` comparison](https://github.com/sindresorhus/got#comparison).

**Comment by matthew-andrews** [comment]
oh wow I'm not sure I have time to put together such a nice comparison table, but I've added a very short note about alternatives here:-
https://github.com/matthew-andrews/isomorphic-fetch#alternatives

In my view the best alternative is not using it at all — just pick up the wonderful node-fetch implementation for backend code and rely on the browser or polyfill.io to ensure fetch is available on the client.
