### ISSUE TITLE
strange dependency requirement uses a random git branch

### ISSUE THREAD

**Issue by crccheck** [matthew-andrews/isomorphic-fetch#19]
Trying to install this from the npm repository runs into this line:
```
"whatwg-fetch": "git+https://github.com/matthew-andrews/fetch#ie9"
```
Which 
1. requires features from a relatively newer build of `npm` than what's in the vanilla ubuntu repository
2. requires git to be installed on the host
3. appears to be just some random branch?

1 & 2 are making `isomorphic-fetch` difficult to get installed into a Docker image I'm currently trying to build.

**Comment by airwin** [comment]
agree

**Comment by tracker1** [comment]
+1 it may be better to publish what-wg fetch client as a separate module in npm, then reference/update against that?

**Comment by matthew-andrews** [comment]
We switched to that branch to get some basic IE9 cors support (did make a PR for this back to the GitHub polyfill — which wasn't accepted)…  plan is to eliminate our need for this which I think is imminent…… (@whererhys do you know if we still IE9?)……

@tracker1 think it's already in npm registry?

**Comment by tracker1** [comment]
Would probably just refer people to [xdomain](https://github.com/jpillora/xdomain) if you need to support older versions of IE...  I didn't know if that specific branch (with IE9 support) was published as a separate module from the github shim.

**Comment by aintgoin2goa** [comment]
This branch doesn't actually work in any browser if you need CORS with cookies.  this line:

https://github.com/matthew-andrews/fetch/blob/master/fetch.js#L246

option should actually be 'include':
https://developer.mozilla.org/en-US/docs/Web/API/Request/credentials

This is a simple fix but there is quite a log of different between githubs fetch and this one, it might be a better idea to refactor out the IE9 stuff into a seperate module or something?

**Comment by matthew-andrews** [comment]
using the main polyfill as of [v2.1.0](https://github.com/matthew-andrews/isomorphic-fetch/releases/tag/v2.1.0)
