### ISSUE TITLE
Upgrade node-fetch to version 2.6.1 or 3.0.0-beta.9

### ISSUE THREAD

**Issue by Yaswanth-Tippireddy** [matthew-andrews/isomorphic-fetch#197]
[https://www.npmjs.com/advisories/1556](https://www.npmjs.com/advisories/1556
)

The dependency on older version of node-fetch has been breaking some packages.

**Comment by s100** [comment]
This problem exists only in `isomorphic-fetch@2`, which depends on `node-fetch@^1.0.1`. I don't know if `isomorphic-fetch@2` is still actively supported... However, the latest version of this package is `isomorphic-fetch@3`, which depends on `node-fetch@^2.6.1` and doesn't have this problem. So, probably the top suggested fix is to upgrade to `isomorphic-fetch@3`.
