### ISSUE TITLE
can I use es7 async/await?

### ISSUE THREAD

**Issue by vyorkin** [matthew-andrews/isomorphic-fetch#24]
example:
```
require('isomorphic-fetch');

(async () => {
  try {
    // request
    let response = await fetch('http://localhost:8088/api/v1/hooy');
    // parsing
    let data = await response.json();
    console.log('data: ', data);
  } catch (error) {
    console.log('error: ', error);
  }
}());
```

sh session:
```
❯ es6 test1.js
error:  [TypeError: Cannot read property 'json' of undefined]
```

where `es6` alias is:
```
function es6() { babel --stage=0 --experimental "$@" | iojs; }
```

I guess it's related to [node-fetch](https://github.com/bitinn/node-fetch), so I've submitted [another issue there](https://github.com/bitinn/node-fetch/issues/27)

**Comment by tracker1** [comment]
@vyorkin why not just alias your es6 to `babel-node --stage 0`?

**Comment by AllenFang** [comment]
I think it should be work with async/await. I use webpack to set the babel load with <code>stage=1&optional=runtime</code>.

**Comment by ZeroCR** [comment]
Why do you have to use "await" twice?
