### ISSUE TITLE
Rename to universal-fetch

### ISSUE THREAD

**Issue by firstdoit** [matthew-andrews/isomorphic-fetch#32]
Just a conversation starter: should this be named `universal-fetch`? 

It seems the community is slowly going in this direction :)

https://medium.com/@mjackson/universal-javascript-4761051b7ae9

**Comment by matthew-andrews** [comment]
Haha.  Thanks for the suggestion.  I need to check the consequences of renaming — bower used to choke but it might be ok now.

**Comment by tracker1** [comment]
@matthew-andrews not sure about npm either... maybe have a `#.minor.0` release that you deprecate with a message related to using the "new" name.

**Comment by matthew-andrews** [comment]
Hmm.. not sure there's a lot of benefit to doing this…  I'm sorry @tracker1 I'm going to close this issue.  Thank you for the suggestion though.
