### ISSUE TITLE
Critical dependencies error with node-fetch encoding

### ISSUE THREAD

**Issue by HriBB** [matthew-andrews/isomorphic-fetch#33]
When I try to build universal react app with redux and isomorphic-fetch, I het this error

```
WARNING in (server) ./~/isomorphic-fetch/~/node-fetch/~/encoding/lib/encoding.js
Critical dependencies:
9:12-34 the request of a dependency is an expression
 @ ./~/isomorphic-fetch/~/node-fetch/~/encoding/lib/encoding.js 9:12-34
```

**Comment by HriBB** [comment]
Some more information https://github.com/bitinn/node-fetch/issues/41

**Comment by matthew-andrews** [comment]
I agree with @bitinn in his comment on that issue.  Our code is not at fault here.  Sorry.
