### ISSUE TITLE
Interceptors / Default Headers

### ISSUE THREAD

**Issue by lynndylanhurley** [matthew-andrews/isomorphic-fetch#37]
I'm trying to include an auth header in each request to my API. 

I can do this with jQuery.ajax using `beforeSend`, and AngularJS has something called [interceptors](https://docs.angularjs.org/api/ng/service/$http#interceptors) which make it really easy.

But I can't figure out how to do this using `fetch`. Any ideas?

**Comment by matthew-andrews** [comment]
Why don't you make a new function?

```js
function makeAuthenticatedRequest(url, opts) {
  opts.headers = opts.headers || {};
  opts.header.Authorization = "a-secret";
  return fetch(url, opts);
}
```

then use that?
