### ISSUE TITLE
May isomorphic-fetch support IE8?

### ISSUE THREAD

**Issue by AnnaSu** [matthew-andrews/isomorphic-fetch#38]
Hello,

As title, is this module support IE8 ? 
Or is going to support it?

Thank you very much.  :smiley:

**Comment by matthew-andrews** [comment]
Hi Anna,

This module relies on the [github fetch client](https://github.com/github/fetch), which does not support IE8 unfortunately … that library actually only _partially_ supports IE**9** so I think IE8 support might be a little bit difficult …… so there's no plan currently to support IE 8.  I'm sorry…

Matt

**Comment by AnnaSu** [comment]
Hi Matt,

I see.

Thank you reply so soon!!!!  :+1:   :100: 

Anna Su

**Comment by tracker1** [comment]
@AnnaSu You can try shimming out your target resource with [xdomain](http://jpillora.com/xdomain) if that's an option, then the fetch polyfill may work, no guarantees... 

----

That said, it may be worth considering if you *really* need IE8-9 support... IE8 support is all but gone now, and IE9-10 are at a point where both could be considerations for removal.

In one of the projects I'm working on, we actually have the following in place to redirect noscript and old IE users to specific destination pages.

```html
  <head>
    ...
    <noscript>
      <META HTTP-EQUIV="refresh" content="0;URL=noscript.html">
    </noscript>
    <!--[if lt IE 10 ]>
      <META HTTP-EQUIV="refresh" content="0;URL=upgradebrowser.html">
    <![endif]-->
```

IE 8-10 are particularly problematic for CORS based requests for API resources that use the `Authentication` header, which many are moving forward... There are some shims to work around the issue, but it's still an issue.

**Comment by matthew-andrews** [comment]
If the data you want to ajax isn't sensitive, you could true use our `jsonp` fetch implementation:-
https://github.com/Financial-Times/n-jsonp-fetch

**Comment by pluma** [comment]
Just a heads up that there is an IE8-compatible fork of github fetch: https://www.npmjs.com/package/fetch-polyfill

I'm considering forking isomorphic-fetch to replace the browser polyfill with the IE8-compatible version.
