### ISSUE TITLE
Please advice: how to POST and accept empty reponse of 204 status?

### ISSUE THREAD

**Issue by Webkadabra** [matthew-andrews/isomorphic-fetch#39]
I have the followng code, which stays as `pending` requiest until timeout error is thrown:

```
fetch(`/api/users/logout?access_token=${token}`, {
        //body: null,
        credentials: 'include',
        method: 'post',
        headers: {
          'Accept': 'application/json, application/xml, text/plain, text/html, *.*',
          'Content-Type': 'application/x-www-form-urlencoded; charset=utf-8'
        },
      })
      .then(response => {
        console.log('Test!'); // It will get here only after a huge timeout, not right after request
        if (response.status === 200) return response.json();
        return response.json();
      })
```

So issue is that I can't make this request really work - it does not get to `then()` part unless i wait few minutes.Please, advice!

**Comment by matthew-andrews** [comment]
It seems likely that the API your calling is just really slow.  Have you tried making the same call with another library?  Or perhaps with `curl`?  At first glance this doesn't look like a problem with `isomorphic-fetch`.
