### ISSUE TITLE
There is no way to specify node-fetch Fetch.Promise

### ISSUE THREAD

**Issue by boo1ean** [matthew-andrews/isomorphic-fetch#43]
If platform doesn't include native promises there is not way to set Fetch.Promise for node-fetch.

```
Error: native promise missing, set Fetch.Promise to your favorite alternative
```

**Comment by tracker1** [comment]
require('isomorphic-fetch');
    fetch.Promise = require('bluebird');

or, before fetch is used/polyfilled

    global.Promise = require('bluebird');
    require('isomorphic-fetch');

Of course, upgrading to Node 0.12 or newer would probably be the better approach.

**Comment by boo1ean** [comment]
@tracker1 first one doesn't work because of [this](https://github.com/matthew-andrews/isomorphic-fetch/blob/master/fetch-npm-node.js#L4-L9)

And second one is not preferable, setting globals on the server doesn't look like a good idea.

Upgrading to 4.* is not a solution for some system unfortunately(

Thanks for a feedback, though!

**Comment by matthew-andrews** [comment]
would happily accept a PR to fix [that](https://github.com/matthew-andrews/isomorphic-fetch/blob/master/fetch-npm-node.js#L4-L9) so that the first option works.

**Comment by hankyates** [comment]
As a temporary workaround does this work?

```
import bluebird from 'bluebird'
import {default as isomorphicFetch} from 'isomorphic-fetch'

bluebird.resolve(fetch('http://some-url')).tap(response => console.log(response))
```

**Comment by matthew-andrews** [comment]
No longer relevant in modern javascript …
