### ISSUE TITLE
'manual' redirect mode is not supported

### ISSUE THREAD

**Issue by parkan** [matthew-andrews/isomorphic-fetch#44]
At least in node (v.4.1.1) passing `{ redirect: 'manual' }` results in `follow` behavior. The normal `opaqueRedirect` behavior is of dubious usefulness on server (I really want to be able to inspect every redirect url in a chain and rewrite them as needed), to be fair.

**Comment by matthew-andrews** [comment]
probably should be fixed in [node-fetch](https://github.com/bitinn/node-fetch) … isomorphic-fetch blindly just passes options through …

**Comment by parkan** [comment]
Got it, thanks. Closing.

**Comment by parkan** [comment]
For anyone wondering about this, it appears to be intentionally not supported as per the standard (though the CORS concerns don't really matter on server):

https://github.com/bitinn/node-fetch/issues/46
https://fetch.spec.whatwg.org/#atomic-http-redirect-handling
