### ISSUE TITLE
Does this library support IE9 CORS?

### ISSUE THREAD

**Issue by niksajanjic** [matthew-andrews/isomorphic-fetch#45]
We are using React and Redux to develop our frontend application. Redux documentation as well as some other examples proposed usage of isomorphic-fetch so we did that as well. The thing is, technically we are not making universal app and we have to support IE9+. Our API is on a different domain and our requests would be firing off from browsers which means we'll have CORS issue with IE9.

We had this issue before with our Angular app and we fixed it using https://github.com/jpillora/xdomain, but I doubt this is something we could use now.

I know we probably had to use https://github.com/github/fetch instead of isomorphic one, but right now it would take few hours to make a switch and fix our mistake. I was going through that library's issues and as far as I can see they merged IE9 CORS support sometime during April https://github.com/github/fetch/pull/79.

I see you started this library before that and I suppose there is no need for this library to support that so my question: Is our only fix going back to fetch or this library still supports IE9 CORS requests?

We are still developing our app locally where we can't reproduce CORS requests (probably there is a way, didn't research it yet) so that is a reason why I ask before I try it myself and see if it works. Thanks in advance.

**Comment by XeeD** [comment]
I can recommend using [connect-modrewrite](https://www.npmjs.com/package/connect-modrewrite)

You create an Express app on the server side and mount the API on (for example) `/api`. All the requests are then forwarded to the correct domain, but for the browser it seems that the API is on the same domain.

The setup is really simple:
```js
const app =express();
app.use(modRewrite([`^/api/(.*)$ https://real-api-url.com/$1 [P]`]));
```

**Comment by niksajanjic** [comment]
Thank you for your answer, turns out in the end that we will have both API and WEB application on same domain so we will not have CORS issue at the end. I will still get back here if I test weather this library has a fallback for IE9 CORS and if I ever try XeeD's proposition and I'll let you know how did it go.

**Comment by matthew-andrews** [comment]
Unfortunately I don't think this can support IE9 CORS
https://github.com/github/fetch#browser-support
