### ISSUE TITLE
Is it safe to use relative paths?

### ISSUE THREAD

**Issue by Dindaleon** [matthew-andrews/isomorphic-fetch#46]
Hello,

I want to know if it is safe to use relative paths when fetching. 

For example: 

```
Use this:  fetch('/api/v1/users')

Instead of: fetch('//domain.com/api/v1/users')
```

**Comment by XeeD** [comment]
@Dindaleon Hi, this will work only in the browser.

What I do is to wrap fetch in another function, something like this
```js
function myFetch(url, options) {
  const finalUrl = IS_BROWSER ? url : `http://myservice.com/${url}`
  fetch(url, options)
}

**Comment by btomala** [comment]
Maybe it is possible to append on the server side host and port on which application is running, it should resolve problem with relative paths.
