### ISSUE TITLE
Fetch Header getting dropped in Node

### ISSUE THREAD

**Issue by jasonadt** [matthew-andrews/isomorphic-fetch#50]
I'm working on an isomorphic React app and we've been happily using this fetch library which has worked well until recently.

**My problem**: Fetch appears to be dropping/removing my `X-NO-CACHE` header in NodeJS (it works fine when calling Fetch from the browser). Our other headers (such as: `accept`) seem to be fine.

Here's how I'm setting the header: `fetchOptions.headers['X-NO-CACHE'] = true;`. I've added tracing to the node-fetch/index.js file and observed the following: 

```
Node Fetch options: 
{ headers: { accept: 'application/json', 'X-NO-CACHE': true },
  credentials: 'same-origin' }

Node Fetch headers: 
Headers { _headers: { accept: [ 'application/json' ] } }

```

**UPDATE**: I just realized that it works after I use: `fetchOptions.headers['X-NO-CACHE'] = 'true';` (needed to use `'true'` instead of `true`).

Please fix this for Node since it works fine on the client and should work the same on the server.

Thanks!
Jason

**Comment by NomadGraphix** [comment]
@jasonadt 
Hello there, I'm considering using this library for similar reasons.
I'm searching the documentation and am coming up empty, how do you set the headers in the first place?

**Comment by NomadGraphix** [comment]
@jasonadt 
Never mind, I'm assuming this is the documentation: https://github.github.io/fetch/

**Comment by matthew-andrews** [comment]
This may be an issue in the upstream projects (node-fetch, whatwg-fetch) rather than this project …
