### ISSUE TITLE
Is it possible to catch net::ERR_CONNECTION_REFUSED?

### ISSUE THREAD

**Issue by tkiethanom** [matthew-andrews/isomorphic-fetch#52]
fetch() throws an error up `Uncaught (in promise) TypeError: Failed to fetch(…)` when it hits net::ERR_CONNECTION_REFUSED. Shouldn't this be caught by the function itself?

**Comment by tkiethanom** [comment]
I've tried to wrap it in a try catch but it still throws the error. 

```javascript
try {
  fetch(apiUrl + '/foo');
}
catch(e){
  console.log(e);
}
```

**Comment by gobengo** [comment]
fetch returns a promise. Try

```javascript
fetch('/foo').catch(function (err) {
  // handle
});
```

**Comment by tkiethanom** [comment]
thanks for the quick response! Is it possible to get the response status in the catch?

**Comment by gobengo** [comment]
If you're getting `ERR_CONNECTION_REFUSED`, that's an error at the transport layer. The connection can't even get far enough to get an HTTP Response that would have a status code.
