### ISSUE TITLE
does isomorphic-fetch support IE8

### ISSUE THREAD

**Issue by xiaodid** [matthew-andrews/isomorphic-fetch#56]
I am using isomorphic-fetch in our react and redux project. and we should support ie8. now we found out that whatwg-fetch fails in ie8 for the reason that xhr.onload failed to be called. xhr.onreadystatechange works fine.

**Comment by matthew-andrews** [comment]
Unfortunately not — the Browser support is dependent on the upstream client side polyfill here:-
https://github.com/github/fetch#browser-support

We use this jsonp fetch library on older browsers:-
https://github.com/Financial-Times/n-jsonp-fetch

**Comment by tracker1** [comment]
@xiaodid FYI, over the next year, IE8 is really going to *not work* on most sites using HTTPS, as the protocol and cypher options in XP are being phased out as they've been compromised in different ways.  This has been true for close to a year, but some sites haven't changed their options yet, to keep IE8 alive.  It's dead, should probably let it die.

**Comment by matthew-andrews** [comment]
@tracker1 that depends on where you are.  in china, IE8 usage is still quite high.

also `n-jsonp-fetch` is useful for loading non-sensitive data from different domains in IE9.
