### ISSUE TITLE
This project seems to be discontinued some one forked it and it is maintaining it?

### ISSUE THREAD

**Issue by lucasfeliciano** [matthew-andrews/isomorphic-fetch#79]

**Comment by matthew-andrews** [comment]
This project is almost nothing… just a few lines of code…  It preceded the existence of `node-fetch`… I really suggest using [`node-fetch`[(https://github.com/bitinn/node-fetch/) directly for node-y things and github's WHATWG fetch for client side things.

**Comment by lucasfeliciano** [comment]
You don't understand.

In my case I have a core made in redux. 
this code is shared between a react-native application and a react web application.

React-native provides me a fetch method built in so I wanted something that I can use in both with the same api.
