### ISSUE TITLE
is it response.blob() implemented?

### ISSUE THREAD

**Issue by sibeliusseraphini** [matthew-andrews/isomorphic-fetch#81]
I'm trying to fetch an image but:

```js
fetch('http://example.com/image.jpg').then(response => response.blob())
```

I'm getting response.blob is undefined

**Comment by matthew-andrews** [comment]
This library is just a very very tiny wrapper around node-fetch.  I believe there's a thread over there that talks about this:- https://github.com/bitinn/node-fetch/issues/78.
