### ISSUE TITLE
where 'isomorphic-fetch' coming from?

### ISSUE THREAD

**Issue by chaomao** [matthew-andrews/isomorphic-fetch#82]
Hi, there
I am interesting about code
`import 'isomorphic-fetch'`
I didn't find any file export 'isomorphic-fetch', where is coming from?

**Comment by AaronHarris** [comment]
If you look in package.json, you'll see `"main": "fetch-npm-node.js"`, which means when you require it (in node), it will pull in the fetch-npm-node.js file. When installing it for the frontend (using bower), you'll see `"main": "fetch-bower.js"` in bower.json. Hope this answers your question.

**Comment by chaomao** [comment]
@AaronHarris , thanks dude, I found the all stuff I want.
