### ISSUE TITLE
IE11 caching responses

### ISSUE THREAD

**Issue by ZeroCR** [matthew-andrews/isomorphic-fetch#88]
Is there a way to avoid this? 

I tried with these but it did not work: 
fetch(`xxxxxx`, {cache: false})
fetch(`xxxxxx`, {cache: 'no-cache'})
fetch(`xxxxxx`, {headers: {'Cache-Control': 'no-cache'}})

To reproduce this you need:
- Dev tools close (if it is open, it works fine).
- It works fine in my localhost, I happens in dev/qa server, so it maybe related to HTTPS.

Regards,

**Comment by pkumar84** [comment]
@ZeroCR  - Did you find the solution for that? if so, may i know how ?

**Comment by ZeroCR** [comment]
@pkumar84  well it looks like this is the default behavior of IE11 beyond this library, I was having the same issue with jquery,

So now I am adding a random number to each request =P.
