### ISSUE TITLE
ReferenceError: self is not defined

### ISSUE THREAD

**Issue by kennetpostigo** [matthew-andrews/isomorphic-fetch#98]
I've incorporated `isomorphic-fetch` into a library I made called [`react-reach`](http://github.com/kennetpostigo/react-reach) and it works great in the browser however when I try it out in node I get the following error in my console:
```js
module.exports = self.fetch.bind(self);
                 ^
ReferenceError: self is not defined
```

I'm not exactly sure why this is going on however heres the library code that uses `isomorphic-fetch`:
```js
import fetch from 'isomorphic-fetch';

export function transport (path, query, queryParams, token) {
  return fetch(path, {
    method: 'POST',
    headers: {
      'Accept': 'application/json',
      'content-type': 'application/json',
      'authorization': token
    },
    body: JSON.stringify({
      query,
      queryParams
    })
  })
  .then((response) => {
    return response.json();
  })
  .then((responseBody) => {
    if (responseBody && responseBody.errors) {
      throw new Error(responseBody.errors);
    }
    return responseBody.data;
  });
}
```
Here is the userland code used in node:
```js
import { reachGraphQL } from 'react-reach';

var imgUri = `http://localhost:8080/users/${req.params.id}/${req.file.originalname}`;

reachGraphQL(`http://localhost:8080/`, `mutation {
  profilePic: updateUser(profilePicture: "${imgUri}"){
    profilePicture
  }
}`)
```

If you know why this may be occurring please let me know as I depend on this library for an application at my job.

**Comment by kennetpostigo** [comment]
Solved it, just placed it in the externals for webpack.

**Comment by jmarceli** [comment]
Hi, I think I've got exact same problem. Could you please provide more details about your solution.

**Comment by kennetpostigo** [comment]
@jmarceli , I realized I was adding webpack into the library build webpack provides. You have to make sure to add it as and external in your webpack file, so that it doesn't try to bundle it. 
```
  externals: [
    {
      isomorphic-fetch: {
        root: 'isomorphic-fetch',
        commonjs2: 'isomorphic-fetch',
        commonjs: 'isomorphic-fetch',
        amd: 'isomorphic-fetch'
      }
    }
  ],
```

This only works if your using webpack. Not sure if your using another build system for making your library.

**Comment by jmarceli** [comment]
That was exactly my issue. Thanks for the solution!

The only required change to your code was wrapping `isomorphic-fetch` in single quotes like this:
```
  externals: [
    {
      'isomorphic-fetch': {
        root: 'isomorphic-fetch',
        commonjs2: 'isomorphic-fetch',
        commonjs: 'isomorphic-fetch',
        amd: 'isomorphic-fetch'
      }
    }
  ],
```

**Comment by marr** [comment]
Is this a regression with webpack v2? I have been previously been able to bundle isomorphic-fetch with webpack, now that I've upgrade to v2 beta I am seeing the `self` error.

**Comment by HoraceShmorace** [comment]
Wait, this isn't a solution. Now it's not available in your build.
